Mirror @2020-02-18

diff --git a/script/git/git-rebuild b/script/git/git-rebuild
--- a/script/git/git-rebuild
+++ b/script/git/git-rebuild
@@ -1,17 +1,50 @@
 #!/usr/bin/zsh
 #Helper to rebase patches and rebuild branches
 
-#PATCH=("origin:upstream:br1,br2")
-#(if upstream is empty looks at the upstream of br1, br2)
-#-> rebase branches onto 'upstream'
-#BUILD=("origin:upstream:br1,br2")
-#(if upsteam is empty looks at the upstream of origin)
-#-> move 'origin' to 'upstream' and merge the branches together
-#Ex for bup: git my rebuild -- -s --build build-arch:build:archlinux,index --build build-python2:build:index patch-origin:master:build,archlinux,index
+# 1) Rebase at once several branches:
+# git rebuild upstream branch1 branch2
+# -> construct an octopus merge of all branches, rebase the octopus and
+# update these branches
+# Options: 
+#   --root root: add all branches that contain root and not merged into upstream
+#    --from root: shortcut for rebasing all branches from root onto new_upstream (ie this is a shortcut for '--root root --onto upstream root')
+#   --rb rebase_options/ -i / --onto branch: passed to rebase
+#   --continue/--abort/...: passed to rebase, then we updated the branch from the octopus position
+
+# 2) Then rebase patches (in case we could not do it via a multi rebase)
+#PATCH=("origin:upstream:br1,br2") #(if upstream is empty looks at the upstream of br1, br2)
+#=> rebase branches onto 'upstream':
+#   git rebase --onto $upstream $origin $branch /
+#   and move $origin to $upstream
+# Note: if origin is empty, simply do: git rebase $upstream $branch
+
+# 3) Then rebuild the integration branches
+#BUILD=("origin:upstream:br1,br2") #(if upstream is empty looks at the upstream of origin)
+#=> move 'origin' to 'upstream' and merge the branches together:
+#   git checkout -B $origin $upstream && git merge $branches
+
+# Options:
+# -s/--save: before rebasing/moving the branches, save them in $OLDBR
+# --save-name: name of $OLDBR (default to old-patches)
+
+#Ex for bup: git my rebuild -- -s --build build-arch:build:archlinux,index --build build-python2:build:index --patch patch-origin:master:build,archlinux,index
+# => rebase the patches build, archlinux, index; then create the
+# integration branch build-python2 on top of build (merging index), and
+# build-arch (merging archlinux, index)
 
 BUILD=()
 PATCH=()
+roots=()
 SAVEBR=
+action=
+from=
+rb_opts=()
+# octomerge_name="refs/hidden/octomerge"
+octomerge_name="_octomerge"
+# Warning: when creating the octomerge we need a standard name (so it will
+# be put in refs/heads). Otherwise rebase does not update the branch name
+# after rebasing. And we need to do git rebase upstream _octomerge (not
+# refs/heads/_octomerge) for this to work
 
 while true;
 do
@@ -21,6 +54,12 @@ do
     --save-name ) shift ; OLDBR=$1; shift ;;
     -b|--build ) shift ; BUILD+=($1); shift ;;
     -p|--patch ) shift ; PATCH+=($1); shift ;;
+    -r|--root ) shift; roots+=($1); shift ;;
+    -f|--from ) shift; from=$1; shift ;;
+    -i ) shift; rb_opts+=('-i') ;;
+    --onto ) shift; rb_opts+=('--onto' $1); shift ;;
+    --rb ) shift; rb_opts+=(${(z)1}); shift ;;
+    --continue|--skip|--abort|--quit|--finish) action=$1; shift ;;
     *) break;; #go to PATCH
   esac
 done
@@ -39,7 +78,7 @@ split_string() {
 
 doorfail() {
 	echo "# $@"
-	$@ || exit 1
+	$@ || exit $?
 }
 
 savebr() {
@@ -48,10 +87,64 @@ savebr() {
 	doorfail git my trivial -- -m "Save branches: $msg" -g -B $OLDBR $OLDBR $@
 }
 
-PATCH+=($@)
 curbr=$(git current-branch -a)
 [[ -z $OLDBR ]] && OLDBR="old-patches"
 [[ -n $SAVEBR ]] && { git rev-parse --verify $OLDBR 2>/dev/null || doorfail git my trivial -- -g -b $OLDBR }
+
+# multi branch rebase
+if [[ -n $action || -n $@ ]]; then
+  if [[ -n $action ]]; then
+    # Pass the action through to git-rebase.
+    [[ $action != --finish ]] && doorfail git rebase $action
+    # Find the branches we used
+    branches=$(git log --format=%s $octomerge_name -1)
+    branches=(${=branches#merging })
+  elif [[ -n $@ ]]; then
+    new_upstream=$1; shift
+    branches=($@)
+    # Fetch all the branches that contain the root of the subtree
+    for root in $roots; do
+      branches+=($(git for-each-ref --contains $root --no-merged $new_upstream --format='%(refname:strip=2)' refs/heads/))
+    done
+    # --from root is a shortcut for rebasing all branches from root onto new_upstream
+    msg="=> rebasing $branches onto $new_upstream"
+    if [[ -n $from ]]; then
+      msg="$msg [from: $from]"
+      branches+=($(git for-each-ref --contains $from --no-merged $new_upstream --format='%(refname:strip=2)' refs/heads/))
+      rb_opts+=("--onto=$new_upstream")
+      new_upstream=$from
+    fi
+    [[ -n $SAVEBR ]] && savebr $branches
+    echo "=> msg"
+
+    # Create the octomerge: a temporary commit that has all the topic branches as parents.
+    # Use the tree from the common ancestor of all the branches. It probably
+    # doesn't matter what tree we use, but the merge-base is a) conveniently
+    # accessible and b) probably the most sensible thing. Conceptually, this
+    # equates to committing an octomerge that undoes everything the topic branches did, which is a well-defined operation.
+    merge_base=$(git merge-base --octopus $branches)
+    octomerge=$(echo 'merging' $branches |
+      git commit-tree $merge_base^{tree} -p `echo $branches | sed -e's/ / -p /g'`)
+    # doorfail git update-ref $octomerge_name $octomerge
+    doorfail git switch -c $octomerge_name $octomerge
+    # And then rebase the octomerge onto the new upstream.
+    doorfail git rebase --rebase-merges $rb_opts $new_upstream
+  fi
+
+  # Move all the old branches to point to the rebased commits.
+  # The parents of the octomerge remain in the same order through the rebase.
+  new_commit_list=($(git rev-parse $octomerge_name^@))
+  echo $branches
+  for index in $(seq 1 $#branches); do
+    branch=${branches[$index]}
+    echo $index, $branch
+    echo "moving $branch (was $(git rev-parse --short $branch))"
+    git branch -f $branch ${new_commit_list[$index]}
+  done
+
+  # git update-ref -d $octomerge_name # clean up.
+  git branch -d $octomerge_name
+fi
 
 for patch in $PATCH; do
 	echo "! patch: $patch"
@@ -89,4 +182,4 @@ for build in $BUILD; do
 	doorfail git merge $branches
 done
 
-doorfail git co $curbr
+doorfail git checkout $curbr
diff --git a/script/git/git-update-worktree b/script/git/git-update-worktree
--- a/script/git/git-update-worktree
+++ b/script/git/git-update-worktree
@@ -3,6 +3,7 @@ GITDIR=$(git rev-parse --git-dir)
 
 #- git update-worktree [--cached/--index] [--reset/--keep-unmerged,--ff] tree
 #- git update-worktree --merge [--index,--keep-unmerged,--ff] tree
+#- git update-worktree --tmp worktree options -- git command to run in tmp worktree
 #- git update-worktree --tmp-index program
 #- git update-worktree --merge-recursive common old new
 #- unmerged=$(git ls-files -u) && git update worktree --restore-unmerged $unmerged
@@ -57,7 +58,7 @@ GITDIR=$(git rev-parse --git-dir)
 #  git-read-tree -m $index
 #or by doing
 #  TMPFILE=.git/index.tmp
-#  cp $GIT_INDEX_FILE .git/index.tmp
+#  cp $GIT_INDEX_FILE $TMPFILE
 #  GIT_INDEX_FILE=$TMPFILE git read-tree -u ...
 #we choose the second option, this let the unmerged entries in the index.
 
@@ -86,6 +87,7 @@ do
 		--index ) shift; indexmode="index" ;;
 		--cached ) shift; indexmode="cached" ;;
 		-m|--merge ) shift; merge=1 ;;
+		--tmp ) shift; temp_worktree=1 ; break ;;
 		--tmp-index ) shift; temp=1 ;;
 		--merge-recursive ) shift; mergerecursive=1 ;;
 		--restore-unmerged ) shift; restoreunmerged=1 ;;
@@ -167,13 +169,33 @@ doautostash() {
 
 . ~/mine/script/git/git-topic-helper
 
-if [[ -n $temp ]]; then
+if [[ -n $temp_worktree ]]; then #--tmp
+	set -e #exit on error
+	opts=()
+	while [[ $# > 0 ]];
+	do
+		case "$1" in
+			-- ) break ;;
+			*) opts+=$1 ; shift ;;
+		esac
+	done
+
+	name=$(basename $(git rev-parse --show-toplevel))
+	git worktree add ~/tmp/worktree_$name $opts
+	cd ~/tmp/worktree_$name
+	eval $@
+	cd -
+	git worktree remove ~/tmp/worktree_$name
+	exit 0
+fi
+
+if [[ -n $temp ]]; then #--tmp-index
 	gth_tmp_index
 	exec "$@"
 fi
 
 doautostash
-if [[ -n $mergerecursive ]]; then
+if [[ -n $mergerecursive ]]; then #--merge-recursive
 	gth_special_branches "$@"
 	branchcommon=$gth_branches_rev[1];
 	branch1=$gth_branches_rev[2];
@@ -186,13 +208,13 @@ if [[ -n $mergerecursive ]]; then
 	exit $?
 fi
 
-if [[ -n $restoreunmerged ]]; then
+if [[ -n $restoreunmerged ]]; then #--restore-unmerged
 	unmerged="$@"
 	restore_unmerged $unmerged
 	exit $?
 fi
 
-if [[ -n $merge ]]; then
+if [[ -n $merge ]]; then #--merge
 	[[ $indexmode == "cached" ]] && abort "--merge and --cached is incompatible"
 	[[ -z $indexmode ]] && index=$(git write-tree)
 	gth_topic "$@"
diff --git a/script/wpa_helper b/script/wpa_helper
--- a/script/wpa_helper
+++ b/script/wpa_helper
@@ -1,12 +1,32 @@
 #!/bin/zsh
 #A lot of this is stolen from wifi-menu in netctl
 
+#wpa_helper scan/add ssid pass/commit/save ssid pass/pass ssid pass
 help() {
-	echo "wpa_helper [-i interface] scan/menu"
-	echo "	add/save/pass ssid pass"
+	echo "wpa_helper [-i interface] *scan/menu/select"
+	echo "	add/save/pass/qr ssid pass"
 	echo "	cli/list/commit"
+	echo "Note: save/pass/commit is for wpa_supplicant only"
 	exit 1
 }
+# add ssid pass: add network via wpa_cli
+# commit: call save_config
+# save ssid pass: add it to wpa_supplicant.conf and reconfigure
+#                 essentially equivalent to add + commit
+# pass ssid pass: same as save but uses the output of wpa_passphrase
+# cli: launch wpa_cli on the correct interface
+# list: list networks already configured
+# scan: scan result
+# menu: filter the scan results, prompt the user and 'add' the selected network
+# select: call menu or add according to whether we have arguments
+#         + if menu is called, pass NOPASS=t to not prompt passwords (so that we may select only networks we know)
+
+# For iwd: add=save -> iwctl station wlan0 connect ssid pass [!commit]
+#          -> pass, menu
+#          cli -> iwctl
+#          list -> iwctl known-networks list
+#          scan -> iwctl station wlan0 scan #it's already on by default
+#                  iwctl station wlan0 get-networks
 
 while true;
 do
@@ -18,30 +38,43 @@ do
 done
 
 if [[ -z "$INTERFACE" ]]; then
-		INTERFACE=(/sys/class/net/*/wireless/)
-		if [[ "${#INTERFACE[@]}" -ne 1 || ! -d "$INTERFACE" ]]; then
-				echo "No interface found in $INTERFACE"
-				exit 255
-		fi
-		INTERFACE=$(basename $(dirname $INTERFACE))
+	INTERFACE=(/sys/class/net/*/wireless/)
+	if [[ "${#INTERFACE[@]}" -ne 1 || ! -d "$INTERFACE" ]]; then
+			echo "No interface found in $INTERFACE"
+			exit 255
+	fi
+	INTERFACE=$(basename $(dirname $INTERFACE))
 fi
-echo "# Using interface $INTERFACE"
+
+mode=
+if systemctl -q is-active iwd; then
+	mode=iwd
+elif systemctl -q is-active wpa_supplicant@$INTERFACE; then
+	mode=wpa
+else
+	echo "Warning: neither iwd nor wpa_supplicant is active for $INTERFACE"
+fi
+echo "# Using interface $INTERFACE [$mode]"
 
 wpa_call() {
-		local args
-		args=("-i" $1)
-		shift
-		wpa_cli $args "$@"
+	local args
+	args=("-i" $1)
+	shift
+	wpa_cli $args "$@"
+}
+
+iwd_call() {
+	iwctl station $INTERFACE $@
 }
 
 wpa_is_active(){
-		[[ $(wpa_call "$1" ping 2> /dev/null) == "PONG" ]]
+	[[ $(wpa_call "$1" ping 2> /dev/null) == "PONG" ]]
 }
 
 wpa_action() {
-		local action=$1 interface=$2
-		echo "systemctl $action wpa_supplicant@$interface.service"
-		systemctl $action "wpa_supplicant@$interface.service"
+	local action=$1 interface=$2
+	echo "systemctl $action wpa_supplicant@$interface.service"
+	systemctl $action "wpa_supplicant@$interface.service"
 }
 
 ## Retrieves the state of an instance of the wpa supplicant
@@ -50,23 +83,23 @@ wpa_action() {
 ##									GROUP_HANDSHAKE, COMPLETED
 # $1: interface name
 wpa_get_state() {
-		local state
-		state=$(wpa_call $1 status | grep -m1 "^wpa_state=") || return 1
-		echo ${state#wpa_state=}
+	local state
+	state=$(wpa_call $1 status | grep -m1 "^wpa_state=") || return 1
+	echo ${state#wpa_state=}
 }
 
 ## Waits until a statement succeeds or a timeout occurs
 # $1: timeout in seconds
 # $2...: condition command
 timeout_wait() {
-		local timeout=$1
-		(( timeout *= 5 ))
-		shift
-		until eval "$*"; do
-				(( timeout-- > 0 )) || return 1
-				sleep 0.2
-		done
-		return 0
+	local timeout=$1
+	(( timeout *= 5 ))
+	shift
+	until eval "$*"; do
+			(( timeout-- > 0 )) || return 1
+			sleep 0.2
+	done
+	return 0
 }
 
 ## Waits while the wpa supplicant is in a listed state
@@ -74,51 +107,134 @@ timeout_wait() {
 # $2: interface name
 # $3...: rejected states
 wpa_wait_while_state() {
-		local timeout=$1 interface=$2
-		shift; shift;
-		states=("$@")
-		timeout_wait "$timeout" \
-			'[[ -z ${(M)states:#$(wpa_get_state $interface)} ]]'
+	local timeout=$1 interface=$2
+	shift; shift;
+	states=("$@")
+	timeout_wait "$timeout" \
+		'[[ -z ${(M)states:#$(wpa_get_state $interface)} ]]'
 }
 
 ## Scan for networks within range
 # $1: interface name
 # $2: fields of the wpa_supplicant scan_results
 wpa_supplicant_scan() {
-		local interface=$1 fields=$2 spawned_wpa=0 essids
+	local interface=$1 fields=$2 spawned_wpa=0 essids
+	[[ -n $interface ]] || return 1
 
-		[[ -n $interface ]] || return 1
+	if ! wpa_is_active $interface; then
+		wpa_action start $interface  || return 1
+		spawned_wpa=1
+	fi
 
-		if ! wpa_is_active $interface; then
-			wpa_action start $interface  || return 1
-			spawned_wpa=1
-		fi
+	wpa_call "$interface" scan > /dev/null || return 1
+	# Wait at least 2 seconds for scan results
+	sleep 2
+	# Sometimes, that is not enough
+	wpa_wait_while_state 7 "$interface" "SCANNING"
+	essids=$(wpa_call "$interface" scan_results |
+			tail -n+2 |
+			sort -rn -k3 |
+			sort -u -k5 |
+			sort -rn -k3 |
+			cut -f"$fields")
+	# Fields are tab delimited
+	# Remove extraneous output from wpa_cli
+	# Sort by strength
+	# Remove duplicates
+	# Re-sort by strength as the removal disorders the list
+	# Cut to the AP/essid fields only
 
-		wpa_call "$interface" scan > /dev/null || return 1
-		# Wait at least 2 seconds for scan results
-		sleep 2
-		# Sometimes, that is not enough
-		wpa_wait_while_state 7 "$interface" "SCANNING"
-		essids=$(wpa_call "$interface" scan_results |
-				tail -n+2 |
-				sort -rn -k3 |
-				sort -u -k5 |
-				sort -rn -k3 |
-				cut -f"$fields")
+	(( spawned_wpa == 1 )) && wpa_action stop "$interface"
+	echo "$essids"
+}
 
-		# Fields are tab delimited
-		# Remove extraneous output from wpa_cli
-		# Sort by strength
-		# Remove duplicates
-		# Re-sort by strength as the removal disorders the list
-		# Cut to the AP/essid fields only
+wpa_scan_result() {
+	#Scan colums are bssid / frequency / signal level / flags / ssid
+	essids=$(wpa_supplicant_scan $INTERFACE 3,4,5)
+	#=> signal_level/flags/ssid
+}
 
-		(( spawned_wpa == 1 )) && wpa_action stop "$interface"
+do_cli() {
+	case $mode in
+		wpa) wpa_cli -i $INTERFACE "$@" ;;
+		iwd) iwctl ;;
+	esac
+}
 
-		echo "$essids"
+do_scan() {
+	case $mode in
+		wpa)
+	wpa_scan_result #signal_level/flags/ssid
+	[[ $? == 0 ]] && echo $essids | awk -F '\t' '{ print $1 " |" $3 "|	" $2}'
+	#See http://stackoverflow.com/questions/2129123/rearrange-columns-using-cut to rearrange columns
+	;;
+		iwd) iwd_call get-networks ;;
+	esac
+}
+
+do_menu() {
+	case $mode in
+		wpa)
+	wpa_scan_result
+	[[ $? == 0 && -n $essids ]] || exit $?
+	[[ -n $essids ]] || exit
+	#essids="-60	[ESS]	foo\n-70	[WPA]	bar"
+	for sel in fzf percol; do
+		command -v $sel >/dev/null && break
+	done
+	line=$(echo $essids | awk -F '\t' '{ print $1 "	" $3 "	" $2}' | $sel)
+	essid=$(echo $line | cut -f2)
+	flags=$(echo $line | cut -f3)
+	if [[ -z $NOPASS && $flags != "[ESS]" ]]; then
+		echo -n "Password: "
+		pass=
+		read pass
+		echo "$(basename $0) add \"$essid\" \"$pass\""
+		do_add $essid $pass
+	else
+		echo "$(basename $0) add \"$essid\""
+		do_add $essid
+	fi
+	;;
+		iwd) result=$(do_scan | fzf --header-lines=4 --ansi $@)
+			# If we put -n1 we only match on the first field. This prevent
+			# matching 'open' networks only. + if a network is already selected,
+			# the first field is '>' and not the network name.
+			# Maybe let the user set its own arguments?
+			# essid=$(echo $result | cut -f1) # this is not tab delimited
+			essid=$(echo $result | awk '{ print $1 }')
+			security=$(echo $result | awk '{ print $2 }')
+			if [[ $essid == '>' ]]; then
+				essid=$(echo $result | awk '{ print $2 }')
+				security=$(echo $result | awk '{ print $3 }')
+			fi
+			if [[ -n $essid ]]; then
+				echo "-> Adding $essid $security"
+				if [[ -z $NOPASS && $security == "psk" ]]; then
+					echo -n "Password: "
+					pass=
+					read pass
+				fi
+				if [[ -n $pass ]]; then
+					do_add -P $pass $essid $security
+				else
+					do_add $essid $security
+				fi
+			fi
+	;;
+	esac
+}
+
+do_list() {
+	case $mode in
+		wpa) wpa_cli -i $INTERFACE list_networks ;;
+		iwd) iwctl known-networks list ;;
+	esac
 }
 
 do_add() {
+	case $mode in
+		wpa)
 	ssid=$1 passphrase=$2
 	[[ -z $passphrase ]] && passphrase="NONE"
 	network=$(wpa_call $INTERFACE add_network)
@@ -130,12 +246,74 @@ do_add() {
 		wpa_call $INTERFACE set_network $network psk "\"$passphrase\""
 	fi
 	wpa_call $INTERFACE enable_network $network
+	;;
+		iwd) iwd_call connect $@; do_scan ;;
+	# Note: the arguments are 'iwctl station $INTERFACE [-P/--passphrase=pass] connect SSID [mode=open/psk/80821x]
+	esac
 }
 
+do_select() {
+	if [[ -n $@ ]]; then
+		do_add $@
+	else
+		NOPASS=t
+		do_menu
+	fi
+}
 
-do_scan() {
-	#Scan colums are bssid / frequency / signal level / flags / ssid
-	essids=$(wpa_supplicant_scan $INTERFACE 3,4,5)
+do_save() {
+	case $mode in
+		wpa)
+	ssid=$1 passphrase=$2
+	[[ -n $ssid ]] || exit 1
+	[[ -z $passphrase ]] && passphrase="NONE"
+	if [[ $passphrase == "NONE" ]]; then
+		sudo cat >>/etc/wpa_supplicant/wpa_supplicant-$INTERFACE.conf <<EOS
+network={
+	key_mgmt=NONE
+	ssid="$ssid"
+}
+EOS
+	else
+		sudo cat >>/etc/wpa_supplicant/wpa_supplicant-$INTERFACE.conf <<EOS
+network={
+	ssid="$ssid"
+	psk="$passphrase"
+}
+EOS
+	fi
+	wpa_call $INTERFACE reconfigure
+	;;
+		iwd) echo "In iwd mode use 'add' rather than 'save'" ;;
+	esac
+}
+
+do_pass() {
+	case $mode in
+		wpa)
+	out=$(wpa_passphrase $@) && echo $out >> /etc/wpa_supplicant/wpa_supplicant-$INTERFACE.conf || echo "Error: $out"
+	wpa_call $INTERFACE reconfigure
+	;;
+		iwd) echo "Not implemented for iwd, do it by hand using wpa_passphrase" ;;
+		# TODO
+	esac
+}
+
+do_commit() {
+	case $mode in
+		wpa) wpa_call $INTERFACE save_config ;;
+		iwd) echo "Action 'commit' is only for wpa_supplicant" ;;
+	esac
+}
+
+do_qr() {
+	local ssid sec password file
+	file="/tmp/wifi.png"
+	ssid=$1; password=$2
+	sec=WPA; [[ -n $3 ]] && sec=$3
+	# -s: size, default to 3
+	qrencode -s 10 -o $file "WIFI:S:$SSID;T:$sec;P:$password;;"
+	qiv $file
 }
 
 action=$1
@@ -144,74 +322,8 @@ if [[ -n $action ]]; then
 else
 	action="scan"
 fi
-
 case $action in
-	cli)
-		wpa_cli -i $INTERFACE "$@" ;;
-	menu)
-		do_scan
-		[[ $? == 0 && -n $essids ]] || exit $?
-		[[ -n $essids ]] || exit
-		#essids="-60	[ESS]	foo\n-70	[WPA]	bar"
-		for sel in fzf percol; do
-			command -v $sel >/dev/null && break
-		done
-		line=$(echo $essids | awk -F '\t' '{ print $1 "	" $3 "	" $2}' | $sel)
-		essid=$(echo $line | cut -f2)
-		flags=$(echo $line | cut -f3)
-		if [[ $flags != "[ESS]" ]]; then
-			echo -n "Password: "
-			pass=
-			read pass
-			echo "$(basename $0) add \"$essid\" \"$pass\""
-			do_add $essid $pass
-		else
-			echo "$(basename $0) add \"$essid\""
-			do_add $essid
-		fi
-		;;
-	scan)
-		do_scan #signal_level/flags/ssid
-		[[ $? == 0 ]] && echo $essids | awk -F '\t' '{ print $1 " |" $3 "|	" $2}'
-		#See http://stackoverflow.com/questions/2129123/rearrange-columns-using-cut to rearrange columns
-		;;
-	list)
-		wpa_cli -i $INTERFACE list_networks
-		;;
-	add)
-		do_add $@
-		;;
-	commit)
-		#use 'wpa_cli -i $INTERFACE save_config' if the config is correct
-		wpa_call $INTERFACE save_config;;
-	save)
-		ssid=$1 passphrase=$2
-		[[ -n $ssid ]] || exit 1
-		[[ -z $passphrase ]] && passphrase="NONE"
-		if [[ $passphrase == "NONE" ]]; then
-			sudo cat >>/etc/wpa_supplicant/wpa_supplicant-$INTERFACE.conf <<EOS
-network={
-	key_mgmt=NONE
-	ssid="$ssid"
-}
-EOS
-		else
-			sudo cat >>/etc/wpa_supplicant/wpa_supplicant-$INTERFACE.conf <<EOS
-network={
-	ssid="$ssid"
-	psk="$passphrase"
-}
-EOS
-		fi
-		wpa_call $INTERFACE reconfigure
-		;;
-	pass)
-			out=$(wpa_passphrase $@) && echo $out >> /etc/wpa_supplicant/wpa_supplicant-$INTERFACE.conf || echo "Error: $out"
-		wpa_call $INTERFACE reconfigure
-		;;
-	*)
-		help
-		;;
+	cli|menu|scan|list|add|commit|save|pass|qr|select) do_$action $@ ;;
+	sel | s ) do_select $@ ;;
+	*) help ;;
 esac
-
-#wpa_helper scan/add ssid pass/commit/save ssid pass/pass ssid pass
