Mirror @2019-05-23

diff --git a/script/archive b/script/archive
--- a/script/archive
+++ b/script/archive
@@ -1,118 +1,242 @@
 #!/bin/zsh
 help() {
-  echo "archive dir: compress dir into a .tax.xz
-archive -u foo: unarchive foo
+	echo "archive dir: compress dir into a .tax.xz
+archive -u foo.tar.xz: unarchive foo
+archive -i foo.tar.xz: infos on foo
 
 OPTIONS:
-  -r|-rm: in compression mode ask to remove the dir
-          in decompression mode ask (or not in -rm) to remove foo"
-  -tmp: extract archive in /tmp
-  exit 1
+	-i: infos on archive
+	-r|--rm: in compression mode ask to remove the dir
+					 in decompression mode ask (or not wit --rm) to remove foo.tar.xz
+	-t/--tmp: extract archive foo in /tmp/archives/foo
+	--tmpdir: specify tmpdir (default to /tmp/archives)
+	--out: specify output file/directory
+	--zip/lrzip: archive mode (rather than tar.xz)"
+	exit 1
 }
 
-UNARCHIVE=
+MODE=archive
 REMOVE=
+SIMPLE=
 TEMP=
-TMPDIR="/tmp/xz"
+TMPDIR="/tmp/archives"
+ext=xz
 OPTIONS=()
 while true;
 do
-  case "$1" in
-    -- ) break ;;
-    -u ) shift ;  UNARCHIVE=true  ;;
-    -tmp) shift; TEMP=true ;;
-    -tmpdir) TMPDIR=$1; shift; TEMP=true ;;
-    -r ) shift; REMOVE="true" ;;
-    -rm ) shift; REMOVE="force" ;;
-    -*) OPTIONS=($OPTIONS $1); shift ;;
-    -h|-help|--help ) shift; help ;;
-    *) break;;
-  esac
+	case $1 in
+		-- ) break ;;
+		-i) shift; MODE=info ;;
+		--zip) shift; ext="zip" ;;
+		--lrz|--lrzip) shift; ext="lrz" ;;
+		-r) shift; REMOVE="true" ;;
+		--rm) shift; REMOVE="force" ;;
+		--out) shift; TARGET=$1; shift ;;
+		--simple) shift; SIMPLE=t ;; #extract in place
+		-u) shift; MODE=unarchive ;;
+		-t|--tmp) shift; TEMP=true ;;
+		--tmpdir) shift; TMPDIR=$1; shift; TEMP=true ;;
+		-*) OPTIONS+=$1; shift ;;
+		-h|-help|--help) shift; help ;;
+		*) break;;
+	esac
 done
 
-doremove() {
-  file=$1
-  case $REMOVE in
-    true ) rm -i $file;;
-    force ) rm $file;;
-  esac
+do_remove() {
+	local file=$1
+	case $REMOVE in
+		true ) rm -i $file;;
+		force ) rm $file;;
+	esac
 }
 
-if [[ -z $UNARCHIVE ]]; then
-  for name in "$@"; do
-    DIR=${name%/}
-    XZFILE="$DIR.tar.xz"
-    echo "***** Archiving $DIR in $XZFILE *********"
-    if [[ -f $XZFILE ]]; then
-      echo "!! $XZFILE exist, rm it? (^C to abort)"
-      rm -i $XZFILE
-    fi
-    tar cvf - $DIR | xz $OPTIONS - > $XZFILE
-    xz -l $XZFILE
+do_remove_dir() {
+	if [[ -n $REMOVE ]]; then
+		echo "!! Erase all dirs $@? (^C to abort)"
+		read
+		rm -rf $@
+	fi
+}
 
-    if [[ -n $REMOVE ]]; then
-      echo "!! Erase dir $DIR? (^C to abort)"
-      read a;
-      rm -rf "$DIR"
-    fi
-  done
+common_root() {
+	ruby - $@ << 'EOS'
+require 'pathname'
+require 'shellwords'
 
-else
-  if [[ -n $TEMP ]]; then
-    #extra files to /tmp
-    mkdir -p $TMPDIR
-    for i in "$@"; do
-      TARGET="${i:t:r}"
-      case "$i" in
-        *.tar* ) 
-          TARGET=${TARGET:t:r}
-          DIR=$TMPDIR/$TARGET
-          mkdir -p $DIR
-          echo "-- $DIR --"
-          tar xvf $i -C $DIR;;
-        *.xz) 
-          FILE=$TMPDIR/$TARGET
-          echo "-- $FILE --"
-          unxz --keep --stdout "$i" > $FILE ;;
-        *) echo "'$i' cannot be extracted" 1>&2; continue ;;
-      esac
-    done
+def common_root(*files)
+	roots=files.map {|f| Pathname.new(f).descend.first.basename}.uniq
+	roots.delete(Pathname.new("__MACOSX"))
+	if roots.count==1
+		roots.first
+	else
+		Pathname.new(".")
+	end
+end
 
-  else
-    setopt extended_glob noclobber
-    for i in "$@"; do
-      if [[ ! -f $i && "$i" == (#s)(https|http|ftp)://* ]] ; then
-        if check_com curl; then
-          WGET_CMD="curl -L -k -s"
-        elif check_com wget; then
-          WGET_CMD="wget -q --no-check-certificate"
-        else
-          print "ERROR: neither wget nor curl is installed" >&2
-          continue
-        fi
-        print "-- Downloading '$i' --"
-        ${=WGET_CMD} "$i"
-      fi
-      if [[ -f $i ]] ; then
-        TARGET="${i:t:r}"
-        echo "-- Extracting archive '$i' --"
-        case "$i" in
-          *.zip|*.jar) unzip "$i" -d $TARGET ;;
-          *.rar ) unrar e -ad $i ;;
-          *.tar* ) tar xvf $i ;; 
-          *.tgz ) tar xvf $i ;; 
-          *.gz) gunzip -c "$i" > $TARGET ;;
-          *.bz2) bunzip2 -c "$i" > $TARGET ;;
-          *.xz) unxz --keep "$i" ;;
-          *.lzma) unlzma --keep "$i" ;;
-          *.lzh) lha x "$i" ;;
-          *.Z) uncompress "$i" ;;
-          *deb) ar -x $i ;;
-          *.7z) 7za x "$i" ;;
-          *) echo "'$i' cannot be extracted" 1>&2; continue ;;
-        esac
-        (( $? == 0 )) && doremove $i
-      fi
-    done
-  fi
-fi
+def extract_root(ar)
+	ar=Pathname.new(ar)
+	if ar.file?
+		ext=ar.extname
+		ext='.tar' if ar.to_s.match(/\.tar\.[^\/]*/)
+		case ext
+		when '.tar'
+			# List archive: `tar tf archive`
+			# Extract to a dir: tar xvf archive -C /target/directory
+			files=`tar -tf #{ar.to_s.shellescape}`.split
+			return common_root(*files)
+		when '.zip'
+			files=`zipinfo -1 #{ar.to_s.shellescape}`.split
+			return common_root(*files)
+		end
+	end
+end
+
+puts extract_root(ARGV.first)
+EOS
+}
+
+show_archive() {
+	local archive=$1
+	case $archive in
+		*.xz ) xz -l $archive ;;
+		*.gz ) gzip -l $archive ;;
+		*.lrz ) lrzip -i $archive ;;
+		*.tar ) tar --list -f $archive ;;
+		*.zip ) zipinfo -t $archive ;; #without '-t' list all files name in $archive
+		# cf aussi 'zipinfo -1' (only list files name), and 'unzip -l'
+	esac
+}
+
+do_archive() {
+	local archive is_file
+	if [[ -n $TARGET ]]; then
+		archive=$TARGET
+	else
+		if [[ $#@ == 1 && -f $1 ]]; then #we have a file
+			archive="$1.$ext"
+			is_file=t #not used
+		else #we have a dir or multiple files/dir
+			case $ext in
+				zip) archive="${1%/}.zip" ;;
+				*) archive="${1%/}.tar.$ext" ;;
+			esac
+		fi
+	fi
+	echo "***** Archiving '$@' in '$archive' *********"
+	if [[ -f $archive ]]; then
+		echo "!! Archive '$archive' already exists, continue? (^C to abort)"
+		show_archive $archive
+		read
+	fi
+	case $archive in
+		*.zip) zip -r $archive $@ ;;
+		*.tar.xz) tar cvf - $@ | xz $OPTIONS - > $archive ;;
+		#note: switch to lrztar -z dir?
+		*.tar.lrz) tar cvf - $@ | lrzip $OPTIONS - > $archive ;;
+		*.xz) cat $@ | xz $OPTIONS - > $archive ;;
+		*.lrz) cat $@ | lrzip $OPTIONS - > $archive ;;
+	esac
+	show_archive $archive
+	(( $? == 0 )) && do_remove_dir $@
+}
+
+# extract to a target
+do_unarchive_to_target() {
+	local archive=$1 target=$2
+	setopt noclobber
+		case $archive in
+			*.tar*|*.tgz|*.zip|*.jar|*.rar|*.7z|*deb) mkdir -p $target ;;
+			*) mkdir -p ${target:h}
+		esac
+		case $archive in
+			*.tar.lrz ) lrzuntar -O $target $archive ;;
+			*.tar*|*.tgz ) tar -C $target -xvf $archive ;;
+			*.zip|*.jar) unzip $archive -d $target ;;
+
+			*.xz ) unxz --keep --stdout $archive > $target ;;
+			*.gz) gunzip -c $archive > $target ;;
+			*.bz2) bunzip2 -c $archive > $target ;;
+			*) echo "'$archive' cannot be extracted to target '$target'" 1>&2; continue ;;
+		esac
+}
+
+# simply extract
+do_unarchive_simple() {
+	local archive=$1
+	case $archive in
+		*.tar.lrz ) lrzuntar $archive ;;
+		*.tar*|*.tgz ) tar -xvf $archive ;;
+		*.zip|*.jar) unzip $archive ;;
+		*.rar ) unrar e -ad $archive ;;
+		*.7z) 7za x $archive ;;
+		*deb) ar -x $archive ;;
+
+		*.lz4) lz4 -d $archive ;;
+		*.lzo) lzop -d $archive ;;
+		*.lzh) lha x $archive ;;
+		*.Z) uncompress $archive ;;
+		*.gz) gunzip -k $archive > $output ;; #we want to keep the archive
+		*.bz2) bunzip2 -k $archive > $output ;;
+		*.zst) unzstd $archive ;;
+		*.lzma) unlzma --keep $archive ;;
+		*.xz) unxz --keep $archive ;;
+		*.lrz ) lrunzip $archive ;;
+		*) echo "'$archive' cannot be extracted" 1>&2; continue ;;
+	esac
+}
+
+do_unarchive() {
+	local archive=$1 target=$2
+	# setopt extended_glob noclobber
+	setopt noclobber
+	local root
+	if [[ -f $archive ]] ; then
+		output=${archive:t:r}
+		case $output in
+			*.tar ) output=${output:t:r} ;; #remove the 'tar' suffix
+		esac
+		if [[ -n $target ]]; then
+			echo "-- Extracting archive '$archive' in '$target' --"
+			do_unarchive_to_target $archive $target
+		else
+			echo "-- Extracting archive '$archive' --"
+			if [[ -n $SIMPLE ]]; then
+				do_unarchive_simple $archive
+			else
+				case $archive in
+					*.tar*|*.tgz|*.zip ) 
+						root=$(common_root $archive)
+						if [[ $root != "." ]]; then
+						echo "# Extracting to the archive root: $root/"
+							do_unarchive_simple $archive 
+						else
+						echo "# The archive root is '.', extracting to: $output/"
+							do_unarchive_to_target $archive $output
+						fi ;;
+					*) do_unarchive_simple $archive ;;
+				esac
+			fi
+		fi
+		(( $? == 0 )) && do_remove $archive
+	fi
+}
+
+#archiving
+case $MODE in
+	info )
+		for i in $@; do
+			echo "## Infos on archive '$i':"
+			show_archive $i
+		done ;;
+	unarchive )
+		if [[ -n $TEMP ]]; then
+			for i in $@; do
+				do_unarchive $i $TMPDIR/${i:t:r}
+			done
+		else
+			for i in $@; do
+				do_unarchive $i $TARGET
+			done
+		fi ;;
+	archive ) do_archive $@ ;;
+esac
diff --git a/script/git/git-current-branch b/script/git/git-current-branch
--- a/script/git/git-current-branch
+++ b/script/git/git-current-branch
@@ -2,166 +2,206 @@
 #git current-branch [-al]: give the name of the current branch
 # -a always print a name, even if detached
 # -l long branch name
+#
 #+also some specific commands to get infos on branch names or state of workdir
+# --clean: check that the worktree is clean
+# --remote: print the default remote
+# --upstream: print the default upstream
+# --rebase: show if branch configured for rebase
+#
+# --name-rev: show the symbolic names of branches
+# --contains: git describe --contains (essentially the same as name-rev)
+# --describe: git describe
+# --fullname: git rev-parse --symbolic-full-name
+# --symbolic: git rev-parse --symbolic
+# --name: git rev-parse --abbrev-ref (note abbrev-ref implies symbolic-full-name)
+# --topic: git-topic-helper
+#
+# Exemples:
+# in a detached HEAD,
+#   git rev-parse --symbolic/--abbrev-ref/--symbolic-full-name HEAD -> HEAD
+#   git describe --contains --all -> master~1
+# dans une branche 'conflict'
+#   git rev-parse --symbolic/--abbrev-ref/--symbolic-full-name @ -> @/conflict/refs/heads/conflict
+#   git describe --all -> heads/conflict
+
+
+# get a real branch name, abort if the refs does not correspond to a branch
+# ie like git rev-parse --symbolic-full-name but does not return HEAD when
+# called in a detached head
+get_branch_name() {
+	curr_branch=$(git rev-parse --symbolic-full-name "${1-HEAD}")
+	case $curr_branch in
+		refs/heads/*) curr_branch="${curr_branch#refs/heads/}" ;;
+		*) return 1 ;;
+	esac
+}
 
 # From git-parse-remote.sh
 #GIT_DIR=$(git rev-parse -q --git-dir) || :;
 
 #are we rebasing by default?
 get_rebase () {
-  curr_branch=$(git symbolic-ref -q HEAD)
-  curr_branch="${curr_branch#refs/heads/}"
-  rebase=$(git config --bool branch.$curr_branch.rebase)
-  if test -z "$rebase"
-  then
-      rebase=$(git config --bool pull.rebase)
-  fi
-  echo $rebase
+	get_branch_name "$@" || return 2
+	rebase=$(git config --bool branch.$curr_branch.rebase)
+	if test -z "$rebase"
+	then
+			rebase=$(git config --bool pull.rebase)
+	fi
+	echo $rebase
+	[[ -z $rebase ]] && return 1
 }
 
 get_default_remote () {
-  curr_branch=$(git symbolic-ref -q HEAD)
-  curr_branch="${curr_branch#refs/heads/}"
-  origin=$(git config --get "branch.$curr_branch.remote")
-  echo ${origin:-origin}
+	get_branch_name "$@" || return 1
+	origin=$(git config --get "branch.$curr_branch.remote")
+	echo ${origin:-origin}
 }
 
 get_remote_merge_branch () {
-  case "$#" in
-  0|1)
-      origin="$1"
-      default=$(get_default_remote)
-      test -z "$origin" && origin=$default
-      curr_branch=$(git symbolic-ref -q HEAD) &&
-      [ "$origin" = "$default" ] &&
-      echo $(git for-each-ref --format='%(upstream)' $curr_branch)
-      ;;
-  *)
-      repo=$1
-      shift
-      ref=$1
-      # FIXME: It should return the tracking branch
-      #        Currently only works with the default mapping
-      case "$ref" in
-      +*)
-    ref=$(expr "z$ref" : 'z+\(.*\)')
-    ;;
-      esac
-      expr "z$ref" : 'z.*:' >/dev/null || ref="${ref}:"
-      remote=$(expr "z$ref" : 'z\([^:]*\):')
-      case "$remote" in
-      '' | HEAD ) remote=HEAD ;;
-      heads/*) remote=${remote#heads/} ;;
-      refs/heads/*) remote=${remote#refs/heads/} ;;
-      refs/* | tags/* | remotes/* ) remote=
-      esac
-      [ -n "$remote" ] && case "$repo" in
-    .)
-        echo "refs/heads/$remote"
-        ;;
-    *)
-        echo "refs/remotes/$repo/$remote"
-        ;;
-      esac
-  esac
+	case "$#" in
+	0|1)
+			origin="$1"
+			default=$(get_default_remote)
+			test -z "$origin" && origin=$default
+			curr_branch=$(git symbolic-ref -q HEAD) &&
+			[ "$origin" = "$default" ] &&
+			echo $(git for-each-ref --format='%(upstream)' $curr_branch)
+			;;
+	*)
+			repo=$1
+			shift
+			ref=$1
+			# FIXME: It should return the tracking branch
+			#				 Currently only works with the default mapping
+			case "$ref" in
+				+*) ref=$(expr "z$ref" : 'z+\(.*\)') ;;
+			esac
+			expr "z$ref" : 'z.*:' >/dev/null || ref="${ref}:"
+			remote=$(expr "z$ref" : 'z\([^:]*\):')
+			case "$remote" in
+				'' | HEAD ) remote=HEAD ;;
+				heads/*) remote=${remote#heads/} ;;
+				refs/heads/*) remote=${remote#refs/heads/} ;;
+				refs/* | tags/* | remotes/* ) remote=
+			esac
+			[ -n "$remote" ] && case "$repo" in
+				.) echo "refs/heads/$remote" ;;
+				*) echo "refs/remotes/$repo/$remote" ;;
+			esac
+	esac
 }
 
 require_clean_work_tree () {
-    # Update the index
-    git update-index -q --ignore-submodules --refresh
-    err=0
+		# Update the index
+		git update-index -q --ignore-submodules --refresh
+		err=0
 
-    # Disallow unstaged changes in the working tree
-    if ! git diff-files --quiet --ignore-submodules --
-    then
-        echo >&2 "cannot $1: you have unstaged changes."
-        git diff-files --name-status -r --ignore-submodules -- >&2
-        err=1
-    fi
+		# Disallow unstaged changes in the working tree
+		if ! git diff-files --quiet --ignore-submodules --
+		then
+				echo >&2 "cannot $1: you have unstaged changes."
+				git diff-files --name-status -r --ignore-submodules -- >&2
+				err=1
+		fi
 
-    # Disallow uncommitted changes in the index
-    if ! git diff-index --cached --quiet HEAD --ignore-submodules --
-    then
-        echo >&2 "cannot $1: your index contains uncommitted changes."
-        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
-        err=1
-    fi
+		# Disallow uncommitted changes in the index
+		if ! git diff-index --cached --quiet HEAD --ignore-submodules --
+		then
+				echo >&2 "cannot $1: your index contains uncommitted changes."
+				git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
+				err=1
+		fi
 
-    if [ $err = 1 ]
-    then
-        echo >&2 "Please commit or stash them."
-        exit 1
-    fi
+		if [ $err = 1 ]
+		then
+				echo >&2 "Please commit or stash them."
+				exit 1
+		fi
 }
 
 ALWAYS=
 while true;
 do
-  case "$1" in
-    -- ) shift; break ;;
-    -a ) shift; ALWAYS="--always" ;; #always print a name
-    -l ) shift; LONG=true ;; #long branch name
-    -al|-la ) shift; LONG=true; ALWAYS="--always" ;; #always print a name
-  --clean ) shift;
-    require_clean_work_tree
-    exit 0
-    ;; #cleaniless state of work tree
-  --remote ) shift;
-    get_default_remote
-    exit 0
-    ;; #print the remote of the current branch
-  --upstream ) shift;
-    get_remote_merge_branch
-    exit 0
-    ;; #print the upstream of the current branch
-    #this is the low level way
-    #the high level way is git rev-parse --abbrev-ref --symbolic-full-name @{u}
-  --rebase ) shift;
-    get_rebase
-    exit 0
-    ;; #does a pull rebase rather than merge?
-  --name-rev ) shift
-    git name-rev "$@" | cut -d ' ' -f 2
-    exit $?
-    ;;
-  --contains ) shift
-    exec git describe --all --contains $ALWAYS "$@"
-    ;;#get the name of a branch
-    #more or less equivalent to git name-rev
-  --describe ) shift
-    exec git describe --all $ALWAYS "$@"
-    ;; #describe the branch
-  --fullname) shift
-    exec git rev-parse --symbolic-full-name "$@"
-    ;;
-  --symbolic) shift
-    exec git rev-parse --symbolic "$@"
-    ;;
-  --name) shift;
-    name=$(git rev-parse --abbrev-ref --symbolic-full-name "$@")
-    [[ -n $ALWAYS && -z $name ]] && name=$(git describe --all --always "$@")
-    echo $name
-    exit $?
-    ;;
-  --topic ) shift
-    . ~/mine/script/git/git-topic-helper
-    gth_topic "$@"
-    echo "$gth_local,$gth_remote,${gth_rest[@]}"
-    exit $?
-    ;; #use git-topic-helper
-  *) break;;
-  esac
+	case "$1" in
+		-- ) shift; break ;;
+		-a ) shift; ALWAYS="--always" ;; #always print a name
+		-l ) shift; LONG=true ;; #long branch name
+		-al|-la ) shift; LONG=true; ALWAYS="--always" ;; #always print a name
+	--clean ) shift;
+		require_clean_work_tree
+		exit $?
+		;; #cleaniless state of work tree
+	--remote ) shift;
+		get_default_remote "$@"
+		exit $?
+		;; #print the remote of the current branch
+	--upstream ) shift;
+		get_remote_merge_branch "$@"
+		exit $?
+		;; #print the upstream of the current branch
+		#this is the low level way
+		#the high level way is git rev-parse --abbrev-ref @{u}
+	--rebase ) shift;
+		get_rebase "$@"
+		exit $?
+		;; #does a pull rebase rather than merge?
+	--name-rev ) shift #git-name-rev - Find symbolic names for given revs
+		git name-rev "$@" | cut -d ' ' -f 2
+		exit $?
+		;;
+	--contains ) shift
+		exec git describe --all --contains $ALWAYS "$@" #describe default to HEAD
+		;;#get the name of a branch
+		#more or less equivalent to git name-rev
+		#eg: master~3
+	--describe ) shift
+		exec git describe --all $ALWAYS "$@"
+		;; #describe the branch #-> master-3-g7bb13ba
+	--fullname) shift
+		exec git rev-parse --symbolic-full-name "${@-HEAD}"
+		;;
+	--symbolic) shift
+		exec git rev-parse --symbolic "${@-HEAD}"
+		;;
+	--name) shift;
+		name=$(git rev-parse --abbrev-ref "${@-HEAD}")
+		[[ -n $ALWAYS && -z $name ]] && name=$(git describe --all --always "$@")
+		echo $name
+		exit $?
+		;;
+	--branch-name ) branch-name "$@" ; exit $? ;;
+	--topic ) shift
+		. ~/mine/script/git/git-topic-helper
+		gth_topic "$@"
+		echo "$gth_local,$gth_remote,${gth_rest[@]}"
+		exit $?
+		;; #use git-topic-helper
+	*) break;;
+	esac
 done
 
 #to read a symbolic link directly:
 #git symbolic-ref [--short] -q HEAD
+# the problem with 'git rev-parse --symbolic-full-name' is that for a
+# detached HEAD, it will print HEAD whereas 'git symbolic-ref HEAD' will
+# print nothing, and exit 1 to show it is not a symbolic ref
 if [[ -z $LONG ]]; then
-  git symbolic-ref --short -q HEAD || {
-    if [[ -n $ALWAYS ]]; then git rev-parse --verify HEAD; fi
-  }
+	branch=$(git rev-parse --symbolic ${1-HEAD})
+	case "$branch" in
+		'') [[ -n $ALWAYS ]] && git rev-parse --short --verify HEAD ;;
+		HEAD) if ! git symbolic-ref --short -q HEAD; then
+			[[ -n $ALWAYS ]] && git rev-parse --short --verify HEAD
+			fi ;;
+		*) echo $branch ;;
+	esac
 else
-  #git rev-parse --symbolic-full-name HEAD || {
-  git symbolic-ref -q HEAD || {
-    if [[ -n $ALWAYS ]]; then git rev-parse --verify HEAD; fi
-  }
+	branch=$(git rev-parse --symbolic-full-name ${1-HEAD})
+	case "$branch" in
+		'') [[ -n $ALWAYS ]] && git rev-parse --verify HEAD ;;
+		HEAD) if ! git symbolic-ref -q HEAD; then
+			[[ -n $ALWAYS ]] && git rev-parse --verify HEAD
+			fi ;;
+		*) echo $branch ;;
+	esac
 fi
